---
include:
  - board: blecorne_left
    shield: nice_view
    artifact-name: bs_corne_left

  - board: blecorne_right
    shield: nice_view
    artifact-name: bs_corne_right
    cmake-args: -DCONFIG_ZMK_STATUS_ADVERTISEMENT=n

  - board: blecorne_left
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n -DCONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n
    artifact-name: reset_left

  - board: blecorne_right
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n -DCONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n
    artifact-name: reset_right
